spring:
  application:
    name: Registration

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: king
    password: queen
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



server:
  port: 5001
